---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world

trigger:
  branch:
  - master
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback