---
kind: pipeline
name: default



stage('Scan with Twistcli') {
  sh './twistcli images scan --address https://console-master-fourthbuild.mredmond.demo.twistlock.com/ -u mredmond_paloaltonetworks_com -p 1qaz2wsx3edc --details $IMAGE'
}

steps:
- name: greeting
  commands:
  - echo hello world

steps:
- name: build
  image: nginx:latest
  commands:
  - sleep 5
  - docker build -t test_container:1 . 


steps:
- name: scan
  image: nginx:latest
  commands:
  - sleep 5
  - apk add curl
  - sh 'curl -k -u mredmond_paloaltonetworks_com:1qaz2wsx3edc --output ./twistcli https://console-master-fourthbuild.mredmond.demo.twistlock.com/api/v1/util/twistcli'
  - sh 'sudo chmod a+x ./twistcli'
  - ./twistcli images scan --address https://console-master-fourthbuild.mredmond.demo.twistlock.com -user mredmond_paloaltonetworks_com --password 1qaz2wsx3edc --details test_container:1

trigger:
  branch:
  - master
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback